In [1]:
birth_year=2001
current_year= 2024
age = current_year - birth_year
print(f'B is {age} years old')

Blossom is 23 years old


In [ ]:
#Learning Numpy

In [7]:
import numpy as np

In [90]:
a =np.array([1,2,3])
b = np.array([7,8,9])

In [92]:
a

array([1, 2, 3])

In [33]:
#getting dimension
a.ndim

1

In [35]:
b.ndim

1

In [37]:
#Shape
b.shape

(3,)

In [141]:
#Get type of array
type(a)

numpy.ndarray

In [143]:
a.dtype

dtype('int32')

Accessing Data/ chaging specific elements,rows, columns
=============


In [110]:
a = np.array([[1,2,3,4,5,6,7] , [8,9,10,11,12,13,14]])

In [112]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [46]:
#To get a specific element(rows(up-dwn),column(left-right)) starts from 0
a[1,5]

13

In [48]:
#get a row (: for all)
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
#get all in column specified
a[:,2]

array([ 3, 10])

In [114]:
#Sum data
A = np.array([7,12, 15,225,1800])
np.sum(A)

2059

In [116]:
#Cal. mean
np.mean(A)

411.8

In [118]:
#Multiple entire array
np.array(A * 2)

array([  14,   24,   30,  450, 3600])

In [120]:
#Create 10 evenly spaced numbers btwn 0, 100
c = np.linspace(0, 100, 10)
c

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [242]:
import pandas as pd


In [244]:
#load data

In [246]:
data = pd.read_csv("C:\\Users\\User\\Downloads\\car_sales.csv")

In [272]:
data.head(20)

Make       Model  Year    Price  Mileage  Age
0      Toyota     Corolla  2019  19500.0    15000    5
1       Honda       Civic  2018  18000.0    22000    6
2        Ford       F-150  2020  35000.0    10000    4
3   Chevrolet      Malibu  2017  16000.0    35000    7
4         Bmw    3 Series  2021  45000.0     5000    3
5      Toyota       Camry  2020  25000.0    12000    4
6       Honda      Accord  2019  23000.0    18000    5
7        Ford      Escape  2018  20000.0    28000    6
8   Chevrolet     Equinox  2020  24000.0    14000    4
9         Bmw          X3  2021  50000.0     7000    3
10     Toyota        RAV4  2019  26000.0    20000    5
11      Honda        CR-V  2020  28000.0    16000    4
12       Ford    Explorer  2017  22000.0    40000    7
13  Chevrolet   Silverado  2021  38000.0     8000    3
14        Bmw    5 Series  2018  35000.0    25000    6
15     Toyota  Highlander  2020  35000.0    15000    4
16      Honda       Pilot  2019  32000.0    22000    5
17       Ford     Mustang  2021  40000.0     5000    3
18  Chevrolet      Camaro  2018  28000.0    30000    6
19        Bmw          X5  2020  55000.0    12000    4

In [250]:
data.describe()

Year         Price       Mileage
count    20.000000     20.000000     20.000000
mean   2019.300000  30725.000000  17950.000000
std       1.301821  10835.462004   9827.324956
min    2017.000000  16000.000000   5000.000000
25%    2018.000000  22750.000000  11500.000000
50%    2019.500000  28000.000000  15500.000000
75%    2020.000000  35750.000000  22750.000000
max    2021.000000  55000.000000  40000.000000

In [252]:
data.dtypes

Make       object
Model      object
Year        int64
Price       int64
Mileage     int64
dtype: object

In [254]:
data.isnull().sum()

Make       0
Model      0
Year       0
Price      0
Mileage    0
dtype: int64

In [256]:
data['Model'].unique()

array(['Corolla', 'Civic', 'F-150', 'Malibu', '3 Series', 'Camry',
       'Accord', 'Escape', 'Equinox', 'X3', 'RAV4', 'CR-V', 'Explorer',
       'Silverado', '5 Series', 'Highlander', 'Pilot', 'Mustang',
       'Camaro', 'X5'], dtype=object)

In [258]:
   unique_values_per_column = data.apply(lambda x: x.unique())  # This will return unique values for each column
   

In [260]:
  print( unique_values_per_column )
   

Make                   [Toyota, Honda, Ford, Chevrolet, BMW]
Model      [Corolla, Civic, F-150, Malibu, 3 Series, Camr...
Year                          [2019, 2018, 2020, 2017, 2021]
Price      [19500, 18000, 35000, 16000, 45000, 25000, 230...
Mileage    [15000, 22000, 10000, 35000, 5000, 12000, 1800...
dtype: object


In [262]:
data['Make'].unique()

array(['Toyota', 'Honda', 'Ford', 'Chevrolet', 'BMW'], dtype=object)

In [264]:
#Remove duplicates
data.drop_duplicates (inplace = True)

In [266]:
#Convert to numeric
data['Price'] = data['Price'].replace('[\\$,]', '', regex=True).astype(float)

In [268]:
#standardize Make column to title
data['Make'] = data['Make'].str.title()

In [270]:
#create a new column Age Based on Year
import datetime
current_year = datetime.datetime.now().year
data['Age'] = current_year - data['Year']

In [274]:
print(data['Age'])

0     5
1     6
2     4
3     7
4     3
5     4
6     5
7     6
8     4
9     3
10    5
11    4
12    7
13    3
14    6
15    4
16    5
17    3
18    6
19    4
Name: Age, dtype: int64


In [276]:
#remove outliers (cars with high mileage)
data = data[data['Mileage'] < data['Mileage'].quantile(0.99)]

In [290]:
print(data.head())
print(data.info())

        Make     Model  Year    Price  Mileage  Age Price_Category
0     Toyota   Corolla  2019  19500.0    15000    5         Budget
1      Honda     Civic  2018  18000.0    22000    6         Budget
2       Ford     F-150  2020  35000.0    10000    4      Mid-Range
3  Chevrolet    Malibu  2017  16000.0    35000    7         Budget
4        Bmw  3 Series  2021  45000.0     5000    3         Luxury
<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 0 to 19
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Make            19 non-null     object 
 1   Model           19 non-null     object 
 2   Year            19 non-null     int64  
 3   Price           19 non-null     float64
 4   Mileage         19 non-null     int64  
 5   Age             19 non-null     int64  
 6   Price_Category  19 non-null     object 
dtypes: float64(1), int64(3), object(3)
memory usage: 1.2+ KB
None


In [208]:
#Ensure the Year columns has only Valid Years within a range
data = data[(data['Year'] >= 1900) & (data['Year'] <= current_year)]

In [280]:
# Create a new column 'PriceCategory' using a lambda function
data['Price_Category'] = data['Price'].apply(lambda x: 'Budget' if x < 20000 else ('Mid-Range' if x <= 40000 else 'Luxury'))

In [282]:
print(data['Price_Category'])

0        Budget
1        Budget
2     Mid-Range
3        Budget
4        Luxury
5     Mid-Range
6     Mid-Range
7     Mid-Range
8     Mid-Range
9        Luxury
10    Mid-Range
11    Mid-Range
13    Mid-Range
14    Mid-Range
15    Mid-Range
16    Mid-Range
17    Mid-Range
18    Mid-Range
19       Luxury
Name: Price_Category, dtype: object


In [288]:
#Standardize Model title
data['Model'] = data['Model'].str.title()

In [292]:
# Remove cars with negative mileage
data = data[data['Mileage'] >= 0]  # Keep only rows where mileage is non-negative
